services:
  - type: web
    name: discord-line-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        value: your_discord_token_here
      - key: LINE_TOKEN
        value: your_line_token_here
      - key: LINE_TO
        value: your_line_user_id_here
